-- =============================================
-- CSE 340 Project - Assignment 2
-- Complete SQL File
-- =============================================

-- =============================================
-- PART 1: Database Setup
-- =============================================

-- Clean up existing objects
DROP TYPE IF EXISTS public.account_type CASCADE;
DROP TABLE IF EXISTS public.inventory CASCADE;
DROP TABLE IF EXISTS public.account CASCADE;
DROP TABLE IF EXISTS public.classification CASCADE;

-- Create account_type ENUM
CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');

-- Create classification table
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Insert classification data
INSERT INTO public.classification (classification_name)
VALUES 
    ('Custom'),
    ('Sport'),
    ('SUV'),
    ('Truck'),
    ('Sedan');

-- Create inventory table
CREATE TABLE public.inventory (
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make character varying NOT NULL,
    inv_model character varying NOT NULL,
    inv_year character(4) NOT NULL,
    inv_description text NOT NULL,
    inv_image character varying NOT NULL,
    inv_thumbnail character varying NOT NULL,
    inv_price numeric(9, 0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying NOT NULL,
    classification_id integer NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- Add foreign key constraint
ALTER TABLE IF EXISTS public.inventory
ADD CONSTRAINT fk_classification 
FOREIGN KEY (classification_id) 
REFERENCES public.classification (classification_id) 
MATCH SIMPLE 
ON UPDATE CASCADE 
ON DELETE NO ACTION;

-- Create account table
CREATE TABLE public.account (
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- =============================================
-- PART 2: Insert Sample Data
-- =============================================

-- Insert Tony Stark as Admin
INSERT INTO public.account (
    account_firstname, 
    account_lastname, 
    account_email, 
    account_password, 
    account_type
) 
VALUES (
    'Tony', 
    'Stark', 
    'tony@starkent.com', 
    'Iam1ronM@n', 
    'Admin'
);

-- Insert sample inventory data
INSERT INTO public.inventory (
    inv_make, inv_model, inv_year, inv_description, 
    inv_image, inv_thumbnail, inv_price, inv_miles, 
    inv_color, classification_id
)
VALUES 
    ('Chevy', 'Camaro', '2018', 'If you want to look cool this is the ar you need! This car has great performance at an affordable price. Own it today!', '/images/camaro.jpg', '/images/camaro-tn.jpg', 25000, 101222, 'Silver', 2),
    ('Batmobile', 'Custom', '2021', 'Ever want to be a super hero? now you can with the batmobile. This car allows you to switch to bike mode at the push of a button.', '/images/batmobile.jpg', '/images/batmobile-tn.jpg', 65000, 2987, 'Black', 1),
    ('FBI', 'Surveillance Van', '2016', 'Do you like police shows? You will feel right at home driving this van, comes complete with survalence equipments for and extra fee of $2,000 a month.', '/images/survan.jpg', '/images/survan-tn.jpg', 20000, 19851, 'Green', 1),
    ('Dog', 'Car', '1997', 'Do you like dogs? Well this car is for you straight from the 90s from Aspen, Colorado we have the orginal Dog Car complete with fluffy ears.', '/images/dog-car.jpg', '/images/dog-car-tn.jpg', 35000, 71632, 'Brown', 1),
    ('Jeep', 'Wrangler', '2019', 'The Jeep Wrangler is small and compact with enough power to get you where you want to go. Its great for everyday driving as well as offroading weather that be on the rocks or in the mud!', '/images/wrangler.jpg', '/images/wrangler-tn.jpg', 28045, 41205, 'Orange', 3),
    ('Lamborghini', 'Adventador', '2016', 'This V-12 engine packs a punch in this sporty car. Make sure you wear your seatbelt and obey all traffic laws. ', '/images/adventador.jpg', '/images/adventador-tn.jpg', 417650, 7103, 'Blue', 2);

-- =============================================
-- PART 3: Tony Stark Operations
-- =============================================

-- 1. UPDATE Tony Stark to Client
UPDATE public.account 
SET account_type = 'Client' 
WHERE account_firstname = 'Tony' 
  AND account_lastname = 'Stark';

-- 2. DELETE Tony Stark
DELETE FROM public.account 
WHERE account_firstname = 'Tony' 
  AND account_lastname = 'Stark';

-- =============================================
-- PART 4: Description Update (Replace 'small interiors')
-- =============================================

-- Update description for all vehicles
UPDATE public.inventory 
SET inv_description = REPLACE(
    inv_description, 
    'small interiors', 
    'a huge interior'
);

-- =============================================
-- PART 5: JOIN Query (Inventory with Classification)
-- =============================================

SELECT 
    i.inv_make,
    i.inv_model,
    c.classification_name
FROM 
    public.inventory i
INNER JOIN 
    public.classification c
    ON i.classification_id = c.classification_id
WHERE 
    c.classification_name = 'Sport';

-- =============================================
-- PART 6: Update Image Paths
-- =============================================

-- Update image paths to include /vehicles prefix
UPDATE public.inventory 
SET 
    inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');

-- =============================================
-- PART 7: Verification Queries
-- =============================================

-- 1. Verify classification data
SELECT 'Classification Data:' as message;
SELECT * FROM public.classification ORDER BY classification_id;

-- 2. Verify inventory count
SELECT 'Inventory Count:' as message;
SELECT COUNT(*) as total_vehicles FROM public.inventory;

-- 3. Verify description update
SELECT 'Description Update Check:' as message;
SELECT 
    inv_make,
    inv_model,
    CASE 
        WHEN inv_description LIKE '%huge interior%' THEN '✓ Updated'
        ELSE '✗ Not updated'
    END as update_status
FROM public.inventory LIMIT 3;

-- 4. Verify JOIN query works
SELECT 'JOIN Query Results:' as message;
SELECT 
    i.inv_make,
    i.inv_model,
    c.classification_name
FROM public.inventory i
JOIN public.classification c ON i.classification_id = c.classification_id
WHERE c.classification_name = 'Sport';

-- 5. Verify image paths updated
SELECT 'Image Path Update Check:' as message;
SELECT 
    inv_make,
    inv_model,
    CASE 
        WHEN inv_image LIKE '/images/vehicles/%' THEN '✓ Updated'
        ELSE '✗ Not updated'
    END as image_status,
    CASE 
        WHEN inv_thumbnail LIKE '/images/vehicles/%' THEN '✓ Updated'
        ELSE '✗ Not updated'
    END as thumbnail_status
FROM public.inventory LIMIT 3;

-- 6. Final success message

BEGIN
    RAISE NOTICE '===============================================';
    RAISE NOTICE 'Assignment 2 SQL Script Completed Successfully!';
    RAISE NOTICE '===============================================';
    RAISE NOTICE 'Created:';
    RAISE NOTICE '  - account_type ENUM';
    RAISE NOTICE '  - classification table (5 records)';
    RAISE NOTICE '  - inventory table (6 sample vehicles)';
    RAISE NOTICE '  - account table';
    RAISE NOTICE '';
    RAISE NOTICE 'Performed Operations:';
    RAISE NOTICE '  ✓ Tony Stark INSERT (as Admin)';
    RAISE NOTICE '  ✓ Tony Stark UPDATE (Admin → Client)';
    RAISE NOTICE '  ✓ Tony Stark DELETE';
    RAISE NOTICE '  ✓ Description update (small interiors → huge interior)';
    RAISE NOTICE '  ✓ JOIN query (inventory + classification)';
    RAISE NOTICE '  ✓ Image path update (/images/ → /images/vehicles/)';
    RAISE NOTICE '===============================================';
END ;

-- =============================================
-- END OF ASSIGNMENT 2 SQL FILE
-- =============================================